///////////////////////////////////////////////////////////
//  EV_Seguro.cs
//  Implementation of the Class EV_Seguro
//  Generated by Enterprise Architect
//  Created on:      12-oct.-2023 13:14:05
//  Original author: sebastianperez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;


namespace API.DataSchema
{
	public class EV_Seguro
	{
        [Key]
        public int IdSeguro { get; set; }
        public string Nombre { get; set; }
        public int? IdCalle { get; set; }
        public int? Altura { get; set; }
		public DateTime? FechaAct { get; set; }

        public bool Habilitado { get; set; }
        public bool Activo { get; set; }
        public virtual EV_Calle? EV_Calle { get; set; }
        public virtual ICollection<EV_Conservadora>? EV_Conservadora { get; set; } = new List<EV_Conservadora>(); // Collection navigation containing dependents
    }
}