version: "3.4"

services:
  identityserver:
    image: identityserverpro
    container_name: identityserverpro
    build:
      context: ./IdentityServer/
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - REACT_APP_AUTH_SERVER_URL=http://localhost:5000
      - REACT_APP_CLIENT_URL=http://localhost:3002
      - REACT_APP_CLIENT_ID=react.client
      - REACT_APP_API_URL=http://localhost:3003

  react:
    image: reactpro
    container_name: reactpro
    build:
      context: ./React/
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3002:3000"
    environment:
      - REACT_APP_AUTH_SERVER_URL=http://localhost:5000
      - REACT_APP_CLIENT_URL=http://localhost:3002
      - REACT_APP_CLIENT_ID=react.client
      - REACT_APP_API_URL=http://localhost:3003
    depends_on:
      - api


  api:
    image: api
    container_name: api
    build:
      context: ./API/
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - REACT_APP_CLIENT_URL=http://localhost:3002
      - REACT_APP_AUTH_SERVER_URL=http://identityserver:5001
    depends_on:
     - identityserver



